import "./globals.css";
import { Inter } from "next/font/google";
import Authprovider from "./component/Authprovider/Authprovider";
const inter = Inter({ subsets: ["latin"] });

import UserProvider from "@/context/userProvider";
export const metadata = {
  title: "BloggedIn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <Authprovider>
      <UserProvider>
        <body className="overflow-hidden overflow-y-auto">{children}</body>
      </UserProvider>
      </Authprovider>
    </html>
  );
}
